language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"

services:
  - mongod

before_script:

notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master